// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: location/location.proto

package locationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Locations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Location            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locations) Reset() {
	*x = Locations{}
	mi := &file_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locations) ProtoMessage() {}

func (x *Locations) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locations.ProtoReflect.Descriptor instead.
func (*Locations) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *Locations) GetItems() []*Location {
	if x != nil {
		return x.Items
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalkingId     string                 `protobuf:"bytes,1,opt,name=walking_id,json=walkingId,proto3" json:"walking_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	Altitude      float64                `protobuf:"fixed64,5,opt,name=altitude,proto3" json:"altitude,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,6,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	Speed         float64                `protobuf:"fixed64,7,opt,name=speed,proto3" json:"speed,omitempty"`
	UserId        string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetWalkingId() string {
	if x != nil {
		return x.WalkingId
	}
	return ""
}

func (x *Location) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Location) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Location) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *Location) GetAltitude() float64 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *Location) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *Location) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *Location) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_location_location_proto protoreflect.FileDescriptor

const file_location_location_proto_rawDesc = "" +
	"\n" +
	"\x17location/location.proto\x12\vlocation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n" +
	"\tLocations\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.location.v1.LocationR\x05items\"\xee\x01\n" +
	"\bLocation\x12\x1d\n" +
	"\n" +
	"walking_id\x18\x01 \x01(\tR\twalkingId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng\x12\x1a\n" +
	"\baltitude\x18\x05 \x01(\x01R\baltitude\x12\x1a\n" +
	"\baccuracy\x18\x06 \x01(\x01R\baccuracy\x12\x14\n" +
	"\x05speed\x18\a \x01(\x01R\x05speed\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userIdBQZOgithub.com/kodai-kumatani/beam-pubsub-to-bigtable/pkg/pb/location/v1;locationv1b\x06proto3"

var (
	file_location_location_proto_rawDescOnce sync.Once
	file_location_location_proto_rawDescData []byte
)

func file_location_location_proto_rawDescGZIP() []byte {
	file_location_location_proto_rawDescOnce.Do(func() {
		file_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)))
	})
	return file_location_location_proto_rawDescData
}

var file_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_location_location_proto_goTypes = []any{
	(*Locations)(nil),             // 0: location.v1.Locations
	(*Location)(nil),              // 1: location.v1.Location
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_location_location_proto_depIdxs = []int32{
	1, // 0: location.v1.Locations.items:type_name -> location.v1.Location
	2, // 1: location.v1.Location.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_location_location_proto_init() }
func file_location_location_proto_init() {
	if File_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_location_location_proto_goTypes,
		DependencyIndexes: file_location_location_proto_depIdxs,
		MessageInfos:      file_location_location_proto_msgTypes,
	}.Build()
	File_location_location_proto = out.File
	file_location_location_proto_goTypes = nil
	file_location_location_proto_depIdxs = nil
}
